# -*- coding: utf-8 -*-
"""Mentor_Balanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8EBgqnDzzzosCdS2kzhZtOoqYTJW2gh

Binary XGBoost
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
from collections import Counter

# === Load the dataset ===
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")  # Replace with actual path

# === Extract sentences and original labels ===
texts = df.iloc[:, 0].astype(str).tolist()   # Hindi sentences (1st column)
original_labels = df.iloc[:, 2].astype(str).tolist()  # Labels (3rd column)

# === Step 1: Merge 'Partially Legitimate' and 'Synthetic' into 'Synthetic' ===
merged_labels = ['Legitimate' if lbl == 'Legitimate' else 'Synthetic' for lbl in original_labels]

# === Step 2: Encode the binary labels ===
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(merged_labels)

# === Step 3: Generate sentence embeddings ===
model = SentenceTransformer('distiluse-base-multilingual-cased-v2')
embeddings = model.encode(texts)

# === Step 4: Filter out rare classes if needed (not really needed for binary) ===
label_counts = Counter(y_encoded)
valid_indices = [i for i, y in enumerate(y_encoded) if label_counts[y] > 1]

X_filtered = np.array(embeddings)[valid_indices]
y_filtered = np.array(y_encoded)[valid_indices]

# === Step 5: Train-test split ===
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered, y_filtered, test_size=0.2, random_state=42, stratify=y_filtered
)

# === Step 6: Train XGBoost Classifier ===
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

# === Step 7: Predict and evaluate ===
y_pred = xgb.predict(X_test)

# === Decode labels for readability ===
y_test_labels = label_encoder.inverse_transform(y_test)
y_pred_labels = label_encoder.inverse_transform(y_pred)

# === Step 8: Report ===
print("Test Accuracy:", accuracy_score(y_test_labels, y_pred_labels))
print("\nClassification Report:\n", classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# === Step 9: Confusion Matrix ===
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")

plt.show()

"""SVM Binary"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sentence_transformers import SentenceTransformer
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder

# 1. Load the dataset
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")

# 2. Extract features and labels
sentences = df.iloc[:, 0].astype(str).tolist()     # Hindi sentences
original_labels = df.iloc[:, 2].astype(str).tolist()  # Original labels

# 3. Merge 'Partially Legitimate' and 'Synthetic' into 'Synthetic'
binary_labels = ['Pure' if label == 'Legitimate' else 'Septic' for label in original_labels]

# 4. Encode binary labels
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(binary_labels)  # Legitimate=0, Synthetic=1

# 5. Generate sentence embeddings
model = SentenceTransformer('distiluse-base-multilingual-cased')
embeddings = model.encode(sentences)

# 6. Split data (use stratify to maintain class balance)
X_train, X_test, y_train, y_test = train_test_split(
    embeddings, encoded_labels, test_size=0.2, random_state=42, stratify=encoded_labels
)

# 7. Train SVM
svm_model = SVC(kernel='linear', C=1.0)
svm_model.fit(X_train, y_train)

# 8. Predict
y_pred = svm_model.predict(X_test)

# 9. Decode for reporting
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = label_encoder.inverse_transform(y_test)

# 10. Evaluate
print("SVM Accuracy (Legitimate vs Synthetic):", accuracy_score(y_test_labels, y_pred_labels))
print("\nClassification Report:")
print(classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Compute confusion matrix
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

# Print confusion matrix as array
print("\nConfusion Matrix (raw values):\n", cm)

# Display as a nice plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_encoder.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

"""Binary KNN"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# === Load the dataset ===
file_path = "/content/Dataset For Research Paper.xlsx"  # Change this to your actual path
df = pd.read_excel(file_path)

# === Extract Hindi text and original labels ===
X = df.iloc[:, 0].astype(str)  # Ensure it's all strings
y_original = df.iloc[:, 2].astype(str)

# === Merge 'Partially Legitimate' and 'Synthetic' into 'Synthetic' ===
y_binary = ['Legitimate' if label == 'Legitimate' else 'Synthetic' for label in y_original]

# === Encode binary labels ===
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y_binary)  # Legitimate = 0, Synthetic = 1

# === Convert text to TF-IDF vectors ===
vectorizer = TfidfVectorizer()
X_transformed = vectorizer.fit_transform(X)

# === Train-test split ===
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# === Train the KNN classifier ===
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

# === Make predictions ===
y_pred = knn.predict(X_test)

# === Decode predictions to labels (optional) ===
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = label_encoder.inverse_transform(y_test)

# === Evaluate the model ===
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy (Legitimate vs Synthetic): {accuracy:.2f}")

# === Optional: Show class-wise performance ===
print("\nClassification Report:")
print(classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# === Confusion Matrix ===
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")

plt.show()

"""Binary CNN"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Conv1D, GlobalMaxPooling1D, Dense, Dropout
from sklearn.metrics import classification_report

# 1. Load dataset
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")  # Replace with actual path

# 2. Extract Hindi sentences and original labels
texts = df.iloc[:, 0].astype(str).tolist()
original_labels = df.iloc[:, 2].astype(str).tolist()

# 3. Merge Partially Legitimate and Synthetic into one class: 'Synthetic'
binary_labels = ['Legitimate' if label == 'Legitimate' else 'Synthetic' for label in original_labels]

# 4. Label encode the binary classes
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(binary_labels)  # Legitimate=0, Synthetic=1
y_categorical = to_categorical(y_encoded, num_classes=2)

# 5. Tokenize and pad text
vocab_size = 10000
max_length = 100
tokenizer = Tokenizer(num_words=vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
padded = pad_sequences(sequences, maxlen=max_length, padding='post', truncating='post')

# 6. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    padded, y_categorical, test_size=0.2, random_state=42, stratify=y_categorical
)

# 7. Build CNN model
embedding_dim = 100
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_length),
    Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dense(2, activation='softmax')  # Binary output
])

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# 8. Train model
model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.1)

# 9. Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy (Legitimate vs Synthetic):", accuracy)

# 10. Optional: Classification report
y_pred_prob = model.predict(X_test)
y_pred = np.argmax(y_pred_prob, axis=1)
y_true = np.argmax(y_test, axis=1)

# Decode to label names
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_true_labels = label_encoder.inverse_transform(y_true)

print("\nClassification Report:")
print(classification_report(y_true_labels, y_pred_labels))

"""Binary NB"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# 1. Load dataset
file_path = "/content/Dataset For Research Paper.xlsx"
df = pd.read_excel(file_path)

# 2. Extract Hindi text and original labels
X = df.iloc[:, 0].astype(str)  # Hindi text column
original_labels = df.iloc[:, 2].astype(str)  # Label column

# 3. Combine 'Partially Legitimate' and 'Synthetic' into 'Synthetic'
binary_labels = ['Legitimate' if label == 'Legitimate' else 'Synthetic' for label in original_labels]

# 4. Encode binary labels (Legitimate = 0, Synthetic = 1)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(binary_labels)

# 5. Convert text to TF-IDF features
vectorizer = TfidfVectorizer()
X_transformed = vectorizer.fit_transform(X)

# 6. Split dataset (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_transformed, y_encoded, test_size=0.1, random_state=42, stratify=y_encoded
)

# 7. Train Naïve Bayes classifier
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train)

# 8. Predict on test set
y_pred = nb_model.predict(X_test)

# 9. Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"Naïve Bayes Model Accuracy (Legitimate vs Synthetic): {accuracy:.2f}")

# Optional: Detailed classification report
y_test_labels = label_encoder.inverse_transform(y_test)
y_pred_labels = label_encoder.inverse_transform(y_pred)

print("\nClassification Report:")
print(classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# === Confusion Matrix ===
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")

plt.show()

"""Binary Logistic Regression"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

# 1. Load the dataset
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")  # Change path if needed

# 2. Extract text and labels
texts = df.iloc[:, 0].astype(str).tolist()
original_labels = df.iloc[:, 2].astype(str).tolist()

# 3. Combine 'Partially Legitimate' and 'Synthetic' into one class
binary_labels = ['Pure' if label == 'Legitimate' else 'Septic' for label in original_labels]

# 4. Encode labels
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(binary_labels)  # Legitimate = 0, Synthetic = 1

# 5. Encode text using SentenceTransformer
model = SentenceTransformer('distiluse-base-multilingual-cased')  # Fast multilingual embedding
X = model.encode(texts, show_progress_bar=True)

# 6. Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42, stratify=y_encoded)

# 7. Train Logistic Regression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

# 8. Predict and evaluate
y_pred = logreg.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy (Legitimate vs Synthetic): {accuracy:.4f}")

# Optional: detailed classification report
y_pred_labels = label_encoder.inverse_transform(y_pred)
y_test_labels = label_encoder.inverse_transform(y_test)

print("\nClassification Report:")
print(classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Compute confusion matrix
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

# Print confusion matrix as array
print("\nConfusion Matrix (raw values):\n", cm)

# Display as a nice plot
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=label_encoder.classes_)
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

# --- Import Required Libraries ---
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# 1️⃣ Load the dataset
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")  # Update path if needed

# 2️⃣ Extract text and labels
texts = df.iloc[:, 0].astype(str).tolist()
original_labels = df.iloc[:, 2].astype(str).tolist()

# 3️⃣ Combine 'Partially Legitimate' and 'Synthetic' into one class
binary_labels = ['Legitimate' if label == 'Legitimate' else 'Synthetic' for label in original_labels]

# 4️⃣ Train-test split
X_train, X_test, y_train, y_test = train_test_split(texts, binary_labels, test_size=0.2, random_state=42, stratify=binary_labels)

# 5️⃣ Text vectorization using TF-IDF
vectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

# 6️⃣ Define individual models
models = [
    ('svm', LinearSVC(random_state=42)),
    ('nb', MultinomialNB()),
    ('knn', KNeighborsClassifier(n_neighbors=5)),
    ('rf', RandomForestClassifier(n_estimators=200, random_state=42)),
    ('dt', DecisionTreeClassifier(random_state=42)),
    ('lr', LogisticRegression(max_iter=1000, random_state=42))
]

# 7️⃣ Create Voting Classifier (majority voting)
voting_clf = VotingClassifier(estimators=models, voting='hard')

# 8️⃣ Train ensemble
voting_clf.fit(X_train_tfidf, y_train)

# 9️⃣ Predictions
y_pred = voting_clf.predict(X_test_tfidf)

# 🔟 Evaluation
accuracy = accuracy_score(y_test, y_pred)
print("✅ Accuracy:", round(accuracy * 100, 2), "%\n")

print("📊 Classification Report:")
print(classification_report(y_test, y_pred))

print("🧩 Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# --- Import Required Libraries ---
import re
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV  # Using CV version for auto-tuning
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sentence_transformers import SentenceTransformer  # --- NEW LIBRARY ---

# 1️⃣ Load the dataset
# Make sure this path is correct for your environment
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")

# 2️⃣ Extract text and labels
texts = df.iloc[:, 0].astype(str).tolist()
original_labels = df.iloc[:, 2].astype(str).tolist()

# 3️⃣ Combine 'Partially Legitimate' + 'Synthetic' into one class
binary_labels = ['Legitimate' if label == 'Legitimate' else 'Synthetic' for label in original_labels]

# 4️⃣ Hindi text cleaning (Simpler cleaning is often better for Transformers)
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\s+', ' ', text).strip() # Just normalize whitespace
    return text

texts_cleaned = [clean_text(t) for t in texts]

# 5️⃣ Train-test split
X_train_text, X_test_text, y_train, y_test = train_test_split(
    texts_cleaned, binary_labels, test_size=0.2, random_state=42, stratify=binary_labels
)

# 6️⃣ --- NEW: Generate Sentence Embeddings ---
# We use a model pre-trained on many languages, including Hindi.
# This model converts each sentence into a 768-dimension vector.
print("Loading sentence transformer model (this may take a minute)...")

# --- THIS IS THE CORRECTED LINE ---
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

print("Generating embeddings for training data...")
X_train_embeddings = model.encode(X_train_text, show_progress_bar=True)

print("Generating embeddings for test data...")
X_test_embeddings = model.encode(X_test_text, show_progress_bar=True)

print("\nEmbeddings generated. Shape:", X_train_embeddings.shape)

# 7️⃣ --- NEW: Train a Classifier on the Embeddings ---
# Now that we have dense vectors (embeddings) instead of sparse TF-IDF,
# we can train a simple, strong classifier on them.
print("Training classifier on embeddings...")
# LogisticRegressionCV automatically finds the best 'C' parameter
clf = LogisticRegressionCV(
    cv=5,
    random_state=42,
    max_iter=1000,
    n_jobs=-1
)
clf.fit(X_train_embeddings, y_train)

# 8️⃣ Predictions and Evaluation
print("Training complete. Evaluating on test set...")
y_pred = clf.predict(X_test_embeddings)

accuracy = accuracy_score(y_test, y_pred)
print("✅ Final Test Accuracy (Embeddings):", round(accuracy * 100, 2), "%\n")

print("📊 Classification Report:")
print(classification_report(y_test, y_pred))

# 🧩 Confusion Matrix + Heatmap
cm = confusion_matrix(y_test, y_pred, labels=['Legitimate', 'Synthetic'])
print("🧩 Confusion Matrix:\n", cm)

plt.figure(figsize=(6,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Legitimate', 'Synthetic'], yticklabels=['Legitimate', 'Synthetic'])
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.title('Confusion Matrix (Sentence Embeddings)')
plt.show()

"""LSTM"""

# -----------------------------------------------------------
# 1️⃣ IMPORTS
# -----------------------------------------------------------
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout

# -----------------------------------------------------------
# 2️⃣ LOAD EXCEL (NO HEADERS)
# -----------------------------------------------------------
df = pd.read_excel("/content/Dataset For Research Paper.xlsx", header=None)

# Column 0 → Hindi sentence
sentences = df.iloc[:, 0].astype(str).tolist()

# Column 2 → Legitimate / Partially Legitimate / Synthetic
original_labels = df.iloc[:, 2].astype(str).str.strip().str.lower().tolist()

# -----------------------------------------------------------
# 3️⃣ CLEAN LABELS
# Combine Partially Legitimate + Synthetic → Synthetic
# -----------------------------------------------------------
cleaned = []
for label in original_labels:
    if label == "legitimate":
        cleaned.append("Legitimate")
    else:
        cleaned.append("Synthetic")

labels = cleaned

print("Class distribution:\n", pd.Series(labels).value_counts())

# -----------------------------------------------------------
# 4️⃣ ENCODE LABELS → 0/1
# -----------------------------------------------------------
label_to_int = {"Legitimate": 0, "Synthetic": 1}
y = np.array([label_to_int[l] for l in labels])

# -----------------------------------------------------------
# 5️⃣ TRAIN–TEST SPLIT
# -----------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    sentences, y, test_size=0.2, random_state=42, stratify=y
)

# -----------------------------------------------------------
# 6️⃣ TOKENIZATION (Hindi supported)
# -----------------------------------------------------------
max_words = 20000
max_len = 50

tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(X_train)

X_train_seq = pad_sequences(
    tokenizer.texts_to_sequences(X_train),
    maxlen=max_len
)

X_test_seq = pad_sequences(
    tokenizer.texts_to_sequences(X_test),
    maxlen=max_len
)

# -----------------------------------------------------------
# 7️⃣ BUILD LSTM MODEL
# -----------------------------------------------------------
model = Sequential([
    Embedding(max_words, 128, input_length=max_len),
    LSTM(128),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

model.summary()

# -----------------------------------------------------------
# 8️⃣ TRAIN MODEL
# -----------------------------------------------------------
history = model.fit(
    X_train_seq, y_train,
    validation_split=0.1,
    epochs=6,
    batch_size=32,
    verbose=1
)

# -----------------------------------------------------------
# 9️⃣ PREDICTIONS
# -----------------------------------------------------------
y_pred = (model.predict(X_test_seq) > 0.5).astype(int).flatten()

# -----------------------------------------------------------
# 🔟 ACCURACY
# -----------------------------------------------------------
accuracy = accuracy_score(y_test, y_pred)
print("\nTest Accuracy: {:.2f}%".format(accuracy * 100))

# -----------------------------------------------------------
# 1️⃣1️⃣ CLASSIFICATION REPORT
# -----------------------------------------------------------
print("\nClassification Report:\n")
print(classification_report(
    y_test,
    y_pred,
    target_names=["Legitimate", "Synthetic"]
))

# -----------------------------------------------------------
# 1️⃣2️⃣ CONFUSION MATRIX
# -----------------------------------------------------------
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            xticklabels=["Legitimate", "Synthetic"],
            yticklabels=["Legitimate", "Synthetic"])

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# -----------------------------------------------------------
# 1️⃣3️⃣ TRAINING CURVES (Important for Paper)
# -----------------------------------------------------------
plt.figure(figsize=(12,4))

# Accuracy Curve
plt.subplot(1,2,1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title("Accuracy Curve")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()

# Loss Curve
plt.subplot(1,2,2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title("Loss Curve")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()

plt.show()

"""ANN"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam

df = pd.read_excel("/content/Dataset For Research Paper.xlsx", header=None)

texts = df.iloc[:, 0].astype(str).tolist()
raw_labels = df.iloc[:, 2].astype(str).str.strip().str.lower().tolist()
binary_labels = []
for lbl in raw_labels:
    if lbl == "legitimate":
        binary_labels.append(0)   # Legitimate
    else:
        binary_labels.append(1)   # Synthetic
X_train, X_test, y_train, y_test = train_test_split(
    texts,
    binary_labels,
    test_size=0.2,
    random_state=42,
    stratify=binary_labels
)
vectorizer = TfidfVectorizer(
    max_features=15000,
    ngram_range=(1,2),
    sublinear_tf=True
)

X_train_vec = vectorizer.fit_transform(X_train).toarray()
X_test_vec = vectorizer.transform(X_test).toarray()
model = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_vec.shape[1],)),
    Dropout(0.4),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()
history = model.fit(
    X_train_vec,
    np.array(y_train),
    validation_split=0.1,
    epochs=10,
    batch_size=32,
    verbose=1
)
y_pred = (model.predict(X_test_vec) > 0.5).astype(int).flatten()

accuracy = accuracy_score(y_test, y_pred)
print(f"\nAccuracy: {accuracy:.4f}\n")

print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=["Legitimate", "Synthetic"]))
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=["Legitimate", "Synthetic"],
    yticklabels=["Legitimate", "Synthetic"],
    cmap="Blues"
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
df = pd.read_excel("/content/Dataset For Research Paper.xlsx", header=None)

texts = df.iloc[:, 0].astype(str).tolist()
raw_labels = df.iloc[:, 2].astype(str).str.strip().str.lower().tolist()

# Binary labels
labels = [0 if l == "legitimate" else 1 for l in raw_labels]
X_train, X_test, y_train, y_test = train_test_split(
    texts,
    labels,
    test_size=0.2,
    random_state=42,
    stratify=labels
)
vectorizer = TfidfVectorizer(
    max_features=20000,
    ngram_range=(1,3),
    sublinear_tf=True
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_vec, y_train)

lr_probs = lr.predict_proba(X_test_vec)[:, 1]
X_train_dense = X_train_vec.toarray()
X_test_dense = X_test_vec.toarray()

ann = Sequential([
    Dense(256, activation='relu', input_shape=(X_train_dense.shape[1],)),
    Dropout(0.4),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

ann.compile(
    optimizer=Adam(1e-3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

ann.fit(
    X_train_dense,
    np.array(y_train),
    epochs=10,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

ann_probs = ann.predict(X_test_dense).flatten()
# Average probabilities
ensemble_probs = (lr_probs + ann_probs) / 2

# Final predictions
y_pred = (ensemble_probs > 0.5).astype(int)
accuracy = accuracy_score(y_test, y_pred)
print(f"\nEnsemble Accuracy: {accuracy:.4f}\n")

print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=["Legitimate", "Synthetic"]))
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    xticklabels=["Legitimate", "Synthetic"],
    yticklabels=["Legitimate", "Synthetic"],
    cmap="Greens"
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Ensemble Confusion Matrix")
plt.show()

"""Gemini"""

!pip install -U google-generativeai

import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    Trainer,
    TrainingArguments
)
from datasets import Dataset
df = pd.read_excel("/content/Dataset For Research Paper.xlsx", header=None)

texts = df.iloc[:, 0].astype(str).tolist()
original_labels = df.iloc[:, 2].astype(str).tolist()

# Combine labels
binary_labels = [
    0 if label == "Legitimate" else 1
    for label in original_labels
]

data = pd.DataFrame({
    "text": texts,
    "label": binary_labels
})

print(data["label"].value_counts())
train_df, test_df = train_test_split(
    data,
    test_size=0.2,
    random_state=42,
    stratify=data["label"]
)

train_ds = Dataset.from_pandas(train_df.reset_index(drop=True))
test_ds = Dataset.from_pandas(test_df.reset_index(drop=True))
model_name = "google/muril-base-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
def tokenize(batch):
    return tokenizer(
        batch["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_ds = train_ds.map(tokenize, batched=True)
test_ds = test_ds.map(tokenize, batched=True)

train_ds = train_ds.rename_column("label", "labels")
test_ds = test_ds.rename_column("label", "labels")

train_ds.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
test_ds.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)
training_args = TrainingArguments(
    output_dir="./muril_bias_model",
    do_train=True,
    do_eval=True,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=20,
    save_strategy="no",
    report_to="none"
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds
)

trainer.train()
preds = trainer.predict(test_ds)

y_pred = np.argmax(preds.predictions, axis=1)
y_true = preds.label_ids

accuracy = accuracy_score(y_true, y_pred)
print(f"\nAccuracy: {accuracy:.4f}\n")

print("Classification Report:\n")
print(classification_report(
    y_true,
    y_pred,
    target_names=["Pure", "Septic"]
))
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(6,4))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=["Pure", "Septic"],
    yticklabels=["Pure", "Septic"]
)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("MuRIL Confusion Matrix")
plt.show()

"""Cross Lingual"""

pip install pandas scikit-learn torch transformers datasets openpyxl matplotlib

import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments

# -----------------------------
# LOAD DATA
# -----------------------------
df = pd.read_excel("/content/Dataset For Research Paper.xlsx")

texts = df.iloc[:, 0].astype(str)
labels_raw = df.iloc[:, 2].astype(str)

labels = labels_raw.apply(
    lambda x: "Legitimate" if x.strip() == "Legitimate" else "Synthetic"
)

encoder = LabelEncoder()
y = encoder.fit_transform(labels)

print("Label mapping:",
      dict(zip(encoder.classes_, encoder.transform(encoder.classes_))))

# -----------------------------
# SPLIT
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    texts, y, test_size=0.2, stratify=y, random_state=42
)

train_df = pd.DataFrame({"text": X_train, "label": y_train})
test_df = pd.DataFrame({"text": X_test, "label": y_test})

train_ds = Dataset.from_pandas(train_df)
test_ds = Dataset.from_pandas(test_df)

# -----------------------------
# TOKENIZER
# -----------------------------
model_name = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_ds = train_ds.map(tokenize, batched=True)
test_ds = test_ds.map(tokenize, batched=True)

train_ds.set_format(type="torch",
                    columns=["input_ids","attention_mask","label"])
test_ds.set_format(type="torch",
                   columns=["input_ids","attention_mask","label"])

# -----------------------------
# MODEL
# -----------------------------
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

# -----------------------------
# TRAINING ARGS (SAFE VERSION)
# -----------------------------
training_args = TrainingArguments(
    output_dir="./bias_model",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    weight_decay=0.01,
    logging_steps=50
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=test_ds
)

# -----------------------------
# TRAIN
# -----------------------------
trainer.train()

# -----------------------------
# PREDICT
# -----------------------------
pred = trainer.predict(test_ds)

y_true = pred.label_ids
y_pred = np.argmax(pred.predictions, axis=1)

# -----------------------------
# METRICS
# -----------------------------
print("\nAccuracy:", accuracy_score(y_true, y_pred))

cm = confusion_matrix(y_true, y_pred)
print("\nConfusion Matrix:\n", cm)

print("\nClassification Report:\n",
      classification_report(y_true, y_pred,
                            target_names=encoder.classes_))

# -----------------------------
# PLOT MATRIX
# -----------------------------
plt.imshow(cm)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.colorbar()
plt.show()

# -----------------------------
# PREDICT FUNCTION
# -----------------------------
def predict_sentence(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        outputs = model(**inputs)
    pred = torch.argmax(outputs.logits, dim=1).item()
    return encoder.inverse_transform([pred])[0]

print(predict_sentence("यह खबर पूरी तरह सही है"))