import sys
# -*- coding: utf-8 -*-
"""Mentor_Balanced.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8EBgqnDzzzosCdS2kzhZtOoqYTJW2gh

Binary XGBoost
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sentence_transformers import SentenceTransformer
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report
from collections import Counter

# === Load the dataset ===
df = pd.read_excel(sys.argv[1])  # Replace with actual path

# === Extract sentences and original labels ===
texts = df.iloc[:, 0].astype(str).tolist()   # Hindi sentences (1st column)
original_labels = df.iloc[:, 2].astype(str).tolist()  # Labels (3rd column)

# === Step 1: Merge 'Partially Legitimate' and 'Synthetic' into 'Synthetic' ===
merged_labels = ['Legitimate' if lbl == 'Legitimate' else 'Synthetic' for lbl in original_labels]

# === Step 2: Encode the binary labels ===
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(merged_labels)

# === Step 3: Generate sentence embeddings ===
model = SentenceTransformer('distiluse-base-multilingual-cased-v2')
embeddings = model.encode(texts)

# === Step 4: Filter out rare classes if needed (not really needed for binary) ===
label_counts = Counter(y_encoded)
valid_indices = [i for i, y in enumerate(y_encoded) if label_counts[y] > 1]

X_filtered = np.array(embeddings)[valid_indices]
y_filtered = np.array(y_encoded)[valid_indices]

# === Step 5: Train-test split ===
X_train, X_test, y_train, y_test = train_test_split(
    X_filtered, y_filtered, test_size=0.2, random_state=42, stratify=y_filtered
)

# === Step 6: Train XGBoost Classifier ===
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

# === Step 7: Predict and evaluate ===
y_pred = xgb.predict(X_test)

# === Decode labels for readability ===
y_test_labels = label_encoder.inverse_transform(y_test)
y_pred_labels = label_encoder.inverse_transform(y_pred)

# === Step 8: Report ===
print("Test Accuracy:", accuracy_score(y_test_labels, y_pred_labels))
print("\nClassification Report:\n", classification_report(y_test_labels, y_pred_labels))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

# === Step 9: Confusion Matrix ===
cm = confusion_matrix(y_test_labels, y_pred_labels, labels=label_encoder.classes_)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=label_encoder.classes_,
            yticklabels=label_encoder.classes_)

plt.xlabel("Predicted label")
plt.ylabel("True label")
plt.title("Confusion Matrix")

plt.savefig(sys.argv[2] + '.png', bbox_inches='tight')
plt.close()
